# Generated by Django 3.2.6 on 2021-08-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='day_1_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='day_5_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='day_7_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='month_1_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='month_3_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='month_6_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='year_1_diff',
            field=models.FloatField(null=True),
        ),
    ]
